import type { Metadata } from "next";

import "./globals.css";
import Layout from "./components/layout/Layoute";
import localFont from "next/font/local";





const samim = localFont({
  src: [
    {
      path: "../public/font/Samim.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/font/Samim-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-samim",
});


const vazirmatn = localFont({
  src: [
    {
      path: "../public/font/Vazir-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/font/Vazir-Bold.woff2",
      weight: "700",
      style: "normal",
    },


  ],
  variable: "--font-vazirmatn",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fn"
      className={`${vazirmatn.variable} ${samim.variable}  h-full antialiased rtl`}
    >
      <body>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  );
}
